config/routes.rb
Semiralabs::Application.routes.draw do 

  match 'playdate' => 'games#playdate'
  match 'update_playdate' => 'games#updatePlaydate'
  match 'feedbacks' => 'feedback#create'

  devise_for :users, :controllers => { :sessions => "sessions", :passwords => "passwords" }
  resources :users, :only => [:show] do
    collection do
      get 'search'
      get 'allofplaytellsusers'
    end
  end
  match 'remove_user' => 'users#remove'
  match 'remove_earlyuser' => 'users#remove_earlyuser'
  match 'users_email_list' => 'users#users_email_list'
  match 'earlyusers_email_list' => 'users#earlyusers_email_list'
  
  resources :friendships do
    collection do
      post 'add'
    end
  end
  match "remove_friendship" => 'friendships#remove'

  namespace :api do
    match 'token/update' => 'tokens#update'
    resources :tokens, :only => [:create, :destroy]

    match 'playdatephoto/all_photos' => 'playdatephotos#all_photos'
    resources :playdatephotos, :only => [:create]

    resources :postcards, :only => [:create]
    match 'postcard/all_photos' => 'postcards#all_photos'
    match 'postcard/num_new_photos' => 'postcards#num_new_photos'

    match 'update_settings' => 'settings#update'
    match 'settings/version_check' => 'settings#version_check'
    match 'twilio_incoming' => 'twilio#incoming'
    match 'twilio_token' => 'twilio#capability_token'
    match 'tokbox_tokens' => 'tokbox#tokbox_tokens'
    match 'playdate_players' => 'playdate#playdate_players'
    match 'playdate/redial' => 'playdate#redial'
    match 'playdate/turn_page' => 'playdate#turn_page'
    match 'playdate/change_book' => 'playdate#change_book'
    match 'playdate/close_book' => 'playdate#close_book'
    match 'playdate/finger_tap' => 'playdate#finger_tap'
    match 'playdate/finger_end' => 'playdate#finger_end'
    match 'playdate/create' => 'playdate#create'
    match 'playdate/details' => 'playdate#show'
    match 'playdate/disconnect' => 'playdate#disconnect'
    match 'playdate/join' => 'playdate#join'
    match 'playdate/check_for_playdate' => 'playdate#check_for_playdate'
    match 'playdate/channel_stats' => 'playdate#channel_stats'
    match 'playdate/generate_ot_session' => 'playdate#generate_ot_session'
    match 'activities/list' => 'activities#list'
    match 'books/list' => 'books#list'
    match 'books/get_nux_book' => 'books#get_nux_book'
    match 'users/all_friends' => 'users#all_friends'
    match 'users/get_status' => 'users#get_status'
    match 'users/create_friendship' => 'users#create_friendship'
    match 'users/create' => 'users#create'
    match 'users/update' => 'users#update'
    match 'users/show' => 'users#show'
    match 'users/change_password' => 'users#change_password'
    match 'users/email_check' => 'users#email_check'
    match 'users/reset_password' => 'users#reset_password'
    match 'users/sign_in' => 'users#sign_in'
    match 'pusher/hook' => 'pusher#hook'
    match 'contacts/create_list' => 'contacts#create_list'
    match 'contacts/show' => 'contacts#show'
    match 'contacts/show_related' => 'contacts#show_related'
    match 'contacts/notify' => 'contacts#notify'
    match 'friendship/create' => 'friendships#create'
    match 'friendship/accept' => 'friendships#accept'
    match 'friendship/decline' => 'friendships#decline'

    match 'games/tictactoe/new_game' => 'tictactoe#new_game'
    match 'games/tictactoe/place_piece' => 'tictactoe#place_piece'
    match 'games/tictactoe/spaces_to_json' => 'tictactoe#spaces_to_json'
    match 'games/tictactoe/indicators_to_json' => 'tictactoe#indicators_to_json'
    match 'games/tictactoe/board_to_json' => 'tictactoe#board_to_json'
    match 'games/tictactoe/end_game' => 'tictactoe#end_game'

    match 'games/memory/new_game' => 'memory#new_game'
    match 'games/memory/play_turn' => 'memory#play_turn'
    match 'games/memory/end_game' => 'memory#end_game'

    match 'games/matching/new_game' => 'matching#new_game'
    match 'games/matching/play_turn' => 'matching#play_turn'
    match 'games/matching/end_game' => 'matching#end_game'

    match 'games/hangman/new_game'  => 'hangman#new_game'
    match 'games/hangman/play_turn' => 'hangman#play_turn'
    match 'games/hangman/end_game'  => 'hangman#end_game'

    match 'contacts/show_related' => 'contacts#show_related'
    match 'contacts/notify' => 'contacts#notify'
    match 'contacts/search' => 'contacts#search'
    
  end
  
  match 'pusher/auth' => 'pusher#auth'
  match '/ipad' => 'ipad#index'
  match '/iPad' => 'ipad#index'
  match '/memory' => 'ipad#index'

  
  match 'early_access' => 'application#earlyAccess' 
  match 'timeline' => 'application#timeline'  
  
  authenticated do
    root :to => 'users#show'
  end 
  root :to => 'application#index'
  
  resources :books do
    resources :pages
  end
  
  resources :activities do
    post :sort, :on => :collection
  end
  match 'newactivity/:activity_type' => 'activities#newactivity', :as => 'newactivity'
    
  match 'update_page' => 'games#updatePage'
  match 'update_from_playdate' => 'games#updateFromPlaydate'
  match 'clear_playdate' => 'games#clearPlaydate'
  match 'disconnect_playdate' => 'games#disconnectPlaydate'
  match 'playdate_requested' => 'games#playdateRequested'
  match 'playdate_disconnected' => 'games#playdateDisconnected'
  
  match 'memory' => 'games#memory'
  match 'update_game' => 'games#updateGame'
  match 'update_game_from_session' => 'games#updateGameFromSession'
  match 'set_time' => 'games#setTime' #for youtube videos
  match 'check_time' => 'games#checkTime'
  

end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_filter :authenticate_user!, :except => [:create, :email_check, :sign_in, :reset_password]
  respond_to :json

  # required params: name, email, password, photo, birthdate, isAccountForChild
  def create
    # Create the user
    user = User.new
    user.username = params[:name]
    user.email = params[:email]
    user.password = params[:password]
    #user.birthday = Date.strptime(params[:birthday], "%Y-%m-%d") 
    user.birthday = params[:birthday]
    
    if !user.save
      puts user.errors.inspect
      return render :status => 153, :json => {:message => "User cannot be created at this time."}
    end

    # Upload profile photo
    profilePhoto = ProfilePhoto.new(:user_id => user.id)
    profilePhoto.photo = params[:photo]

    if !profilePhoto.save
      return render :status => 154, :json => {:message => "User photo cannot be created at this time."}
    end

    # Check if someone invited this user to PlayTell
    # If so, make a joint friendship between them
    contactNotification = ContactNotification.where("email = ?", user.email).order('created_at desc').first
    unless contactNotification.nil?
      friend = User.find(contactNotification.user_id)
      unless friend.nil?
        # Create a new friendship
        friendship = Friendship.new
        friendship.user_id = friend.id
        friendship.friend_id = user.id
        friendship.status = true
        friendship.responded_at = DateTime.now
        friendship.save
        
        # Notify Pusher rendezvous channel of friendship approved
        Pusher["presence-rendezvous-channel"].trigger('friendship_accepted', {
          :initiatorID => friend.id,
          :friendID    => user.id
        })
        
        # Log analytics event
        @mixpanel.track("Friendship Accepted",
          :distinct_id => user.username,
          :user_id => user.id,
          :friend_username => friend.username,
          :friend_id => friend.id)
      end
    end

    render :status => 200, :json => {:message => "User created #{user.id}"}
  end
  
  # required params: user_id, user=>{<user params to update>}
  # use for updating all fields except password
  def update
    if params[:user_id].nil? or params[:user_id].empty?
      return render :status => 400, :json => {:message => 'User_id is missing'} 
    end
    
    user = User.find(params[:user_id])
    
    # Replace profile photo
    if !params[:user][:photo].blank?
      profilePhoto = ProfilePhoto.new(:user_id => user.id)
      profilePhoto.photo = params[:user][:photo]

      if !profilePhoto.save
        return render :status => 154, :json => {:message => "User photo cannot be created at this time."}
      end
    end
        
    if user.update_attributes(params[:user])
      puts user.errors.inspect
      return render :status => 200, :json => {:message => "User updated #{user.id}", :profile_photo => user.profile_photo}
    end
    return render :status => 400, :json => {:message => "User cannot be updated at this time.", :details => user.errors.inspect}
  end
  
  def show
    if params[:user_id].nil? or params[:user_id].empty?
      return render :status => 400, :json => {:message => 'User id missing'} 
    end
    
    user = User.find(params[:user_id])
    return render :status => 200, :json => {:user => user}
  end
  
  # required params: user_id, user=>{:current_password=>"", :password=>""}
  def change_password
    if params[:user_id].nil? or params[:user_id].empty?
      return render :status => 400, :json => {:message => 'User id missing'} 
    end
    
    user = User.find(params[:user_id])
    if user.update_with_password(params[:user])
      puts user.errors.inspect
      return render :status => 200, :json => {:message => "User password updated #{user.id}"}
    end
    return render :status => 400, :json => {:message => "User password cannot be updated at this time.", :details => user.errors.inspect}
    
  end

  # required params: user_id
  # returns user objects for all of the given user's friends
  def all_friends
    u = User.find(params[:user_id])
    return render :status => 150, :json => {:message => "User not found."} if u.nil?

    # Give each friendship a status (confirmed, pending-them, or pending-you)
    # Give each a user status (available, playdate, pending)
    friends = []
    u.allApprovedAndPendingFriendships.each do |friendship|
      # Friendship status
      if friendship.user_id == u.id
        friend_id = friendship.friend_id
      else
        friend_id = friendship.user_id
      end

      # Find the user
      begin
        friend = User.find(friend_id)
      rescue ActiveRecord::RecordNotFound => e
        # Delete friendship if friend is not found!
        friendship.destroy
        next
      end

      friendHash = friend.as_playmate(friendship)
      friends << friendHash
    end
    
    render :status=>200, :json=>{:friends => friends}
  end
  
  # required params: user_ids
  def get_status
    # Verify ids
    return render :status => 151, :json => {:message => 'User ids missing'} if params[:user_ids].nil? || params[:user_ids].empty?
    ids = params[:user_ids].split(',').map!{|id| id.to_i};
    return render :status => 151, :json => {:message => 'User ids missing'} if ids.empty?
    
    # Find all users
    user_statuses = []
    ids.each do |id|
      user = User.find(id)
      return render :status => 150, :json => {:message => "User {#{id}} not found."} if user.nil?
      
      # Check status
      if (user.status != User::CONFIRMED)
        # User is pending (aka. hasn't installed the app yet)
        user_statuses << {:id => id, :status => 'pending'}
      elsif Playdate.count(:conditions => ["(player1_id = ? or player2_id = ?) and status != ? and !(player1_id = ? or player2_id = ?)",
        id, id, Playdate::DISCONNECTED, current_user.id, current_user.id]) > 0
        # User is either connecting to a playdate or in a playdate
        user_statuses << {:id => id, :status => 'playdate'}
      else
        # User is available
        user_statuses << {:id => id, :status => 'available'}
      end
    end
    
    # Return all statuses
    render :status => 200, :json => {:status => user_statuses}
  end

  # required params: email
  def email_check
    user = User.find_by_email(params[:email])

    # Return user's id?
    if !user.nil? && !params[:return_user].nil? && params[:return_user] == 'true'
      return render :status => 200, :json => {:available => false, :user_id => user.id}
    end
    
    render :status => 200, :json => {:available => user.nil?}
  end
  
  # required params: user_id
  def reset_password
    if params[:email].blank? 
      return render :status => 400, :json => {:message => 'Email is missing'} 
    end
    
    u = User.find_by_email(params[:email])
    if u.nil? 
      return render :status => 400, :json => {:message => 'No user with that email found'} 
    end
    
    u.send_reset_password_instructions
    render :status => 200, :json => {:new_authentication_token => u.authentication_token}
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'playdates'
  before_filter :authenticate_user!
  before_filter :pusher, :only => [:show]
  layout :chooseLayout
  
  def show
    @user = current_user
    if !@user.confirmed?
      redirect_to ipad_path
    end
    u = current_user
    @new_friends = User.all.select { |friend| friend.id != u.id && u.isFriend?(friend).nil? }
    
    @users = []

    #for playdate
    @feedback = Feedback.new
    @books = Book.all
  
  end
    
  def search
    @users = User.search(params[:search])
  end
  
  # for admin
  def allofplaytellsusers
    @peeps = User.order("id DESC")
    @earlypeeps = EarlyUser.order("id DESC")
    @playdates = Playdate.order("id DESC")
  end
  
  #for admin
  def remove
    @user = User.find(params[:user_id])
    @user.destroy unless @user.blank?
    redirect_to allofplaytellsusers_users_path
  end
  
  #for admin
  def remove_earlyuser
    @user = EarlyUser.find(params[:user_id])
    @user.delete unless @user.blank?
    redirect_to allofplaytellsusers_users_path
  end
  
  #for admin
  def users_email_list
    @users = User.order("id DESC")
  end
  
  def earlyusers_email_list
    @earlyusers = EarlyUser.order("id DESC")
  end
  
  def chooseLayout 
    case action_name
    when 'show'
      'playdates'
    else
      'admin'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_friends.erb
<div class="friends">
	<% for friend in @current_user.allFriends %>
		<div class="friend" data-friendid="<%=friend.id%>">
			<div class="call-button hidden">
				<p class="inline-block left"><a href="#" id="accept-link" class="sprite"></a></p>
				<p class="inline-block right"><a href="#" id="reject-link" class="sprite"></a></p>
			</div>
			<div class="friend-image-wrapper">
				<a href="#" class="friend-item <%= 'disabled' if !friend.confirmed? %>" data-friendid="<%=friend.id%>">
				<%= image_tag friend.profile_photo.blank? ? 
					"photos/default.jpg" : friend.profile_photo, 
					:alt => friend.displayName, 
					:class => "friend-item" %>
				<div class="friend-name"><%= friend.displayName %></div>					
				<%= image_tag "user_online.png", 
					:alt => friend.displayName, 
					:class => "presence online" %>
				<%= image_tag "user_offline.png", 
					:alt => friend.displayName, 
					:class => "presence hidden offline" %>
				<%= image_tag "user_pressed.png", 
					:alt => friend.displayName, 
					:class => "presence hidden pressed" %>
				</a>
				</div>
		</div>
	<% end %>
	
	<!--<div class="friend add-friend">
		<p><a href="#" id="add-friend"></a></p>
	</div>
	-->
	<div class="call-button hidden">
		<p class="inline-block left"><a href="#" id="accept-link" class="sprite"></a></p>
		<p class="inline-block right"><a href="#" id="reject-link" class="sprite"></a></p>
	</div>
	
</div>

app/views/users/_friends.html.erb
<div class="friends">
	<% for friend in @current_user.allFriends %>
		<div class="friend">
			<%= form_tag playdate_path, :class => 'playdate_form' do %>
				<%= hidden_field_tag 'friend_id', friend.id, :id => 'friend_id' %>
				<%= submit_tag friend.displayName %>
			<% end %>
		</div>
	<% end %>
	<div class="friend" id="add-friend"><%= image_tag "add_person.png" %></div>
</div>

app/views/users/_users.erb
<% for user in @users %>
	<p>
		<%= user.fullName %> 
		<%= link_to "Add as Playmate", friendships_path(:friend_id => user), :method => :post %>
	</p>
<% end %>

app/views/users/_users.html.erb
<% for user in @users %>
	<p>
		<%= user.fullName %> 
		<% if current_user != user && !current_user.isFriend?(user) %>
			<%= link_to "Add as Playmate", friendships_path(:friend_id => user), :method => :post %>
		<% end %>
	</p>
<% end %>

app/views/users/allofplaytellsusers.erb
<% content_for :head do %>
	<%= javascript_include_tag 'playdate' %>
	
	<script type="text/javascript">
		var tablet;
		$(document).ready(function() {
			<% if tablet_device? %>
				tablet = true;
			<% end %>
		});

	</script>

<% end %>
<h3><%= link_to "Toybox Activities >>", activities_path %></h3>
<br>
<div class="admin">
	<div class="user-container inline-block admin-div">
		<h1>PlayTell Users (<%= @peeps.count %>)</h1> 
		<h4><%= link_to "Email list >>", users_email_list_path %></h4>
		<br>
		<% for user in @peeps %>
			<h3>[<%= user.id %>] <%= user.displayName %></h3> 
			<%= link_to 'Delete User', remove_user_path(:user_id => user.id) %>
			<p><%= user.email %></p>
			<p>Token: <%= user.device_tokens.blank? ? 'none' : user.device_tokens.first.token %></p>
			<ul>
			<% for friend in user.allFriends %>
				<li>
					<%= friend.displayName %>
					<%= link_to 'Delete Friendship', remove_friendship_path(:user_id => user.id, :friend_id => friend.id) %>
				</li>
			<% end %>
			<%= form_tag add_friendships_path, :method => 'post' do %>
			  <p>
			    <%= text_field_tag :friend_id, nil, :placeholder => 'Enter friend ID' %>
			    <%= hidden_field_tag :user_id, user.id %>
			    <%= submit_tag "Create Friendship", :name => nil %>
			  </p>	
			<% end %>
			</ul>
		<% end %>
	</div>
	<div class="early-user-container inline-block admin-div">
		<h1>Early User Signups (<%= @earlypeeps.count %>)</h1>
		<h4><%= link_to "Email list >>", earlyusers_email_list_path %></h4>
		<br>
		<p>Key: </p>
		<p>Owns iPad (0=no, 1=yes)</p>
		<p>Has kidz (0=no, 1=has kidz, 2=vid chats w/ kidz)
		<% for user in @earlypeeps %>
			<h3><%= user.username %></h3>
			<%= link_to 'Delete User', remove_earlyuser_path(:user_id => user.id) %>
			<p><%= user.email %></p>
			<p>Owns iPad: <%= user.owns_iPad %></p>
			<p>Had kidz: <%= user.has_kids %></p>
		<% end %>
	</div>
	<div class="playdates-container inline-block admin-div">
		<h1>Playdates (<%= @playdates.count %>)</h1>
		<% for playdate in @playdates %>
			<h3>#<%= playdate.id %> on <%= l playdate.created_at.in_time_zone('Pacific Time (US & Canada)'), :format => :short %></h3>
			<p>Player IDs: <%= playdate.player1_id %>, <%= playdate.player2_id %></p>
			<p>Duration: <%= playdate.duration %> min</p>
			<% if !playdate.disconnected? %>
				<p><%= link_to 'Enter Playdate', '/playdate?playdate='+playdate.id.to_s %></p>
			<% end %>
		<% end %>
	</div>

	
</div>

app/views/users/earlyusers_email_list.html.erb
<h1>PlayTell Beta SignUps - Email list (<%= @earlyusers.count %>)</h1> 
<div class="admin-div">
	<% for user in @earlyusers %>
		<p><%= user.email %></p>
	<% end %>
</div>

app/views/users/new.erb
<div class="content">
	<h1>Sign Up</h1>
	<%= form_for @user do |f| %>
		<% if @user.errors.any? %>
			<div class="error-messages">
				<h2>Wait! There's a problem</h2>
				<ul>
					<% for message in @user.errors.full_messsages do %>
						<li><%= message %></li>
					<% end %>
				</ul>	
			</div>
		<% end %>
		<p>
		<%= f.label :username %>
		<%= f.text_field :username %>
		</p>
		<p>
		<%= f.label :password %>
		<%= f.password_field :password %>
		</p>	
		<p>
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation %>
		</p>
		<%= submit_tag "Sign Up", :class => "blue" %>
	<% end %>
</div>

app/views/users/new.html.erb
<div class="content">
	<h1>Sign Up</h1>
	<%= form_for @user do |f| %>
		<% if @user.errors.any? %>
			<div class="error-messages">
				<h2>Wait! There's a problem</h2>
				<ul>
					<% for message in @user.errors.full_messsages do %>
						<li><%= message %></li>
					<% end %>
				</ul>	
			</div>
		<% end %>
		<p>
		<%= f.label :username %>
		<%= f.text_field :username %>
		</p>
		<p>
		<%= f.label :password %>
		<%= f.password_field :password %>
		</p>	
		<p>
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation %>
		</p>
		<%= submit_tag "Sign Up", :class => "blue" %>
	<% end %>
</div>

app/views/users/search.js.erb
<% if @users.empty? %>
	$("#users").html("<p>No results found.</p>");	
<% else %>
	$("#users").html("<%= escape_javascript(render("users")) %>");
<% end %>

app/views/users/show.erb
<% content_for :head do %>
	
	<script type="text/javascript">
		
		$(document).ready(function() { 			
			checkForPlaydateRequest(); 
			enableDialpadButtons();
			enableButtons();
		});
		
	</script>
	
<% end %>

<div class="mainContainer">

	<div class="chat-content row">
		<div class="cam-container">
			<div class="playmate-cam-container inline-block cam"></div>		
			<div class="my-cam-container inline-block cam">
				<%= image_tag current_user.profile_photo %>
				<div class="friend-name"><%= current_user.displayName %></div>					
			</div>
		</div>
	</div>
	
	<div class="user-profile">
				
		<div class="clouds"></div>
	
		<div class="dialpad">
			<div class="dialpad-header">
				<p>Who will play today?&nbsp</p>
			</div>		
			<%= render :partial => "friends" %>
		</div>
	
		<div class="dialpad-logo-container"><%= image_tag "dialpad_logo.png" %></div>
	
		<div class="overlay hidden"></div>

		<div class="lightbox hidden" id="find-lightbox">
			<div id="find-lightbox-text">
				<h2>Find Playmates</h2>
				<%= form_tag search_users_path, :remote => true, :method => 'get', :id => "playmate-search" do %>
				  <p>
				    <%= text_field_tag :search, params[:search] %>
				    <%= submit_tag "Search", :name => nil %>
				  </p>	
				<% end %>
				<div id="users">
					<%= render "users" %>
				</div>
			</div>
			<button class="close close-x blue">X</button>	
		</div>
		
	</div>

</div>

app/views/users/show.html.erb
<div class="black height100">
	<%= render :partial => "friends" %>

	<div class="lightbox hidden" id="join-lightbox">
	</div>

	<div class="lightbox hidden" id="find-lightbox">
		<div id="find-lightbox-text">
			<h2>Find Playmates</h2>
			<%= form_tag search_users_path, :remote => true, :method => 'get', :id => "playmate-search" do %>
			  <p>
			    <%= text_field_tag :search, params[:search] %>
			    <%= submit_tag "Search", :name => nil %>
			  </p>	
			<% end %>
			<div id="users">
				<%= render "users" %>
			</div>
		</div>
		<button class="close close-x blue">X</button>	
	</div>
</div>

<script type="text/javascript">
	var t;
	
	$(document).ready(function() {
		clearTimeout(t);
		checkForPlaydateRequest();
		
		$('#join-playdate').click(function(){
			clearTimeout(t);
		});
		
		$('.find-playmates-link').click(function() {
			$('#find-lightbox').lightbox_me({
		    	centered: true,
				onLoad: function() {
					$('#find-lightbox-text').find('input[type=text]:first').focus();
				}
			});
		});
		
		$("#add-friend").click(function() {
			$("#find-lightbox").lightbox_me();			
		});

	});
	
	function checkForPlaydateRequest() {
		$.getScript("/playdate_requested.js");
		t = setTimeout("checkForPlaydateRequest()", 5000);
	}
	
	function checkForDisconnect(p) {
		$.getScript("/playdate_disconnected.js?playdate="+p);
		t = setTimeout("checkForDisconnect(p)", 1000)
	}
</script>

app/views/users/users_email_list.html.erb
<h1>PlayTell Users - Email list (<%= @users.count %>)</h1> 
<div class="admin-div">
	<% for user in @users %>
		<p><%= user.email %></p>
	<% end %>
</div>