config/routes.rb
Semiralabs::Application.routes.draw do 

  match 'playdate' => 'games#playdate'
  match 'update_playdate' => 'games#updatePlaydate'
  match 'feedbacks' => 'feedback#create'

  devise_for :users, :controllers => { :sessions => "sessions", :passwords => "passwords" }
  resources :users, :only => [:show] do
    collection do
      get 'search'
      get 'allofplaytellsusers'
    end
  end
  match 'remove_user' => 'users#remove'
  match 'remove_earlyuser' => 'users#remove_earlyuser'
  match 'users_email_list' => 'users#users_email_list'
  match 'earlyusers_email_list' => 'users#earlyusers_email_list'
  
  resources :friendships do
    collection do
      post 'add'
    end
  end
  match "remove_friendship" => 'friendships#remove'

  namespace :api do
    match 'token/update' => 'tokens#update'
    resources :tokens, :only => [:create, :destroy]

    match 'playdatephoto/all_photos' => 'playdatephotos#all_photos'
    resources :playdatephotos, :only => [:create]

    resources :postcards, :only => [:create]
    match 'postcard/all_photos' => 'postcards#all_photos'
    match 'postcard/num_new_photos' => 'postcards#num_new_photos'

    match 'update_settings' => 'settings#update'
    match 'settings/version_check' => 'settings#version_check'
    match 'twilio_incoming' => 'twilio#incoming'
    match 'twilio_token' => 'twilio#capability_token'
    match 'tokbox_tokens' => 'tokbox#tokbox_tokens'
    match 'playdate_players' => 'playdate#playdate_players'
    match 'playdate/redial' => 'playdate#redial'
    match 'playdate/turn_page' => 'playdate#turn_page'
    match 'playdate/change_book' => 'playdate#change_book'
    match 'playdate/close_book' => 'playdate#close_book'
    match 'playdate/finger_tap' => 'playdate#finger_tap'
    match 'playdate/finger_end' => 'playdate#finger_end'
    match 'playdate/create' => 'playdate#create'
    match 'playdate/details' => 'playdate#show'
    match 'playdate/disconnect' => 'playdate#disconnect'
    match 'playdate/join' => 'playdate#join'
    match 'playdate/check_for_playdate' => 'playdate#check_for_playdate'
    match 'playdate/channel_stats' => 'playdate#channel_stats'
    match 'playdate/generate_ot_session' => 'playdate#generate_ot_session'
    match 'activities/list' => 'activities#list'
    match 'books/list' => 'books#list'
    match 'books/get_nux_book' => 'books#get_nux_book'
    match 'users/all_friends' => 'users#all_friends'
    match 'users/get_status' => 'users#get_status'
    match 'users/create_friendship' => 'users#create_friendship'
    match 'users/create' => 'users#create'
    match 'users/update' => 'users#update'
    match 'users/show' => 'users#show'
    match 'users/change_password' => 'users#change_password'
    match 'users/email_check' => 'users#email_check'
    match 'users/reset_password' => 'users#reset_password'
    match 'users/sign_in' => 'users#sign_in'
    match 'pusher/hook' => 'pusher#hook'
    match 'contacts/create_list' => 'contacts#create_list'
    match 'contacts/show' => 'contacts#show'
    match 'contacts/show_related' => 'contacts#show_related'
    match 'contacts/notify' => 'contacts#notify'
    match 'friendship/create' => 'friendships#create'
    match 'friendship/accept' => 'friendships#accept'
    match 'friendship/decline' => 'friendships#decline'

    match 'games/tictactoe/new_game' => 'tictactoe#new_game'
    match 'games/tictactoe/place_piece' => 'tictactoe#place_piece'
    match 'games/tictactoe/spaces_to_json' => 'tictactoe#spaces_to_json'
    match 'games/tictactoe/indicators_to_json' => 'tictactoe#indicators_to_json'
    match 'games/tictactoe/board_to_json' => 'tictactoe#board_to_json'
    match 'games/tictactoe/end_game' => 'tictactoe#end_game'

    match 'games/memory/new_game' => 'memory#new_game'
    match 'games/memory/play_turn' => 'memory#play_turn'
    match 'games/memory/end_game' => 'memory#end_game'

    match 'games/matching/new_game' => 'matching#new_game'
    match 'games/matching/play_turn' => 'matching#play_turn'
    match 'games/matching/end_game' => 'matching#end_game'

    match 'games/hangman/new_game'  => 'hangman#new_game'
    match 'games/hangman/play_turn' => 'hangman#play_turn'
    match 'games/hangman/end_game'  => 'hangman#end_game'

    match 'contacts/show_related' => 'contacts#show_related'
    match 'contacts/notify' => 'contacts#notify'
    match 'contacts/search' => 'contacts#search'
    
  end
  
  match 'pusher/auth' => 'pusher#auth'
  match '/ipad' => 'ipad#index'
  match '/iPad' => 'ipad#index'
  match '/memory' => 'ipad#index'

  
  match 'early_access' => 'application#earlyAccess' 
  match 'timeline' => 'application#timeline'  
  
  authenticated do
    root :to => 'users#show'
  end 
  root :to => 'application#index'
  
  resources :books do
    resources :pages
  end
  
  resources :activities do
    post :sort, :on => :collection
  end
  match 'newactivity/:activity_type' => 'activities#newactivity', :as => 'newactivity'
    
  match 'update_page' => 'games#updatePage'
  match 'update_from_playdate' => 'games#updateFromPlaydate'
  match 'clear_playdate' => 'games#clearPlaydate'
  match 'disconnect_playdate' => 'games#disconnectPlaydate'
  match 'playdate_requested' => 'games#playdateRequested'
  match 'playdate_disconnected' => 'games#playdateDisconnected'
  
  match 'memory' => 'games#memory'
  match 'update_game' => 'games#updateGame'
  match 'update_game_from_session' => 'games#updateGameFromSession'
  match 'set_time' => 'games#setTime' #for youtube videos
  match 'check_time' => 'games#checkTime'
  

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  acts_as_list
  has_one :book, :dependent => :destroy
  has_one :game, :dependent => :destroy
  
  def book_attributes=(book_attributes)
    create_book(book_attributes.except(:num_pages))
    num_pages = book_attributes[:num_pages].to_i
    if book.pages.count != num_pages
      book.pages.delete_all
      num_pages.times do |page_num| 
        book.pages.create({:page_num => page_num+1, 
                           :page_text => ""})
      end
    end
  end
  
  def game_attributes=(game_attributes)
    create_game(game_attributes)
  end

  def as_json(options={})
    is_book = !self.book.nil?
    a = { :id => self.id,
      :title => self.title,
      :is_book => is_book }
    if is_book
      a.merge!(:book_id => self.book.id)
    else
      a.merge!(:game_id => self.game.client_id)
    end
    return a
  end

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_filter :authenticate_user!
  layout 'activities'
  
  def index 
    @activities = Activity.order(:position).all
  end
  
  def new
  end
  
  def newactivity
    @activity = Activity.new
    if params[:activity_type] == "book" 
      @activity.build_book(:image_only => 1)
      render 'newbook'
    else
      @activity.build_game
      render 'newgame'
    end   
  end
  
  def create
    @activity = Activity.new(params[:activity])
    if @activity.save
      flash[:notice] = "Successfully created activity."
      redirect_to activities_path
    else
      render :action => 'newactivity', :activity_type => params[:activity_type]
    end
  end
  
  def edit
    @activity = Activity.find(params[:id])
    if !@activity.book.blank?
      render 'editbook'
    else
      render 'editgame'
    end
  end
  
  def update
    @activity = Activity.find(params[:id])
    
    if @activity.update_attributes(params[:activity])
      flash[:notice] = "Successfully updated activity."
      redirect_to activities_path
    else
      render :action => 'edit'
    end
  end
  
  def sort
    @activities = Activity.all
    @activities.each do |a|
      a.position = params['activity'].index(a.id.to_s) + 1
      a.save
    end
    
    render :nothing => true
    end
  
  def reorder_toybox
    
  end
  
  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy
    flash[:notice] = "Successfully deleted activity."
    redirect_to activities_path
  end
  
end

app/controllers/api/activities_controller.rb
class Api::ActivitiesController < ApplicationController
  include Rails.application.routes.url_helpers
  skip_before_filter :verify_authenticity_token
  respond_to :json

  def list
    a = Activity.where("publish = 1").order(:position)

    response = []
    a.each do |activity| 
      next if activity.book.blank?
      
      pages = []
      book = activity.book
      book.pages.order(:page_num).each do |page|
          pages << {
            :url    => url_for(book_page_url(book, page.page_num)),
            #:bitmap => "http://playtell.s3.amazonaws.com/books/#{book.id.to_s}/page#{page.page_num.to_s}.jpg"
            :bitmap => "#{S3_BUCKET_NAME}/books/#{book.image_directory}/page#{page.page_num.to_s}"
          }
      end
      response << {
        :activity_id  => activity.id,
        :book_id      => book.id,
        :current_page => 1,
        :cover        => {
            :front => {
            :url    => url_for(book_url(book)),
            :bitmap => "#{S3_BUCKET_NAME}/books/#{book.image_directory}/cover_front"
            }
        },
        :pages        => pages,
        :total_pages  => book.pages.size
      }
    end
    
    render :status=>200, :json=>{:activities => a, :books => response}
  end
    
end

app/views/activities/_bookform.erb
<%= form_for @activity do |f| %>
	<% if @activity.errors.any? %>
		<div class="error-messages">
			<h2>Wait! There's a problem</h2>
			<ul>
				<% for message in @activity.errors.full_messsages do %>
					<li><%= message %></li>
				<% end %>
			</ul>	
		</div>
	<% end %>
	<p>
	<%= f.label 'Book Title' %>
	<%= f.text_field :title, :required => true %>
	</p>
	
	<%= fields_for 'activity[book_attributes]', @activity.book do |book_form| %>
		<p>
		<%= book_form.label 'Name of S3 image directory' %>
		<%= book_form.text_field :image_directory, :required => true %>
		</p>	
		<p>
		<%= book_form.label 'Number of Pages' %> : <%= @activity.book.pages.count %> 
		<%= select_tag 'activity[book_attributes][num_pages]',  options_for_select([ 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25 ], @activity.book.pages.count) %>
		</p>
		<p>
		<%= book_form.label 'Image-only? (i.e. text is baked into the images)' %>
		<%= book_form.radio_button :image_only, '1' %>Yes <%= book_form.radio_button :image_only, '0' %>No
		</p>
	<% end %>
	
	<p>
	<%= f.label 'Publish to Toybox?' %>
	<%= f.radio_button :publish, '1' %>Yes <%= f.radio_button :publish, '0' %>No
	</p>
	
	<% if !@activity.book.image_only? %>
		<h3>Page Text</h3>
		<%= render :partial => 'pages/page', :collection => @activity.book.pages %>
	<% else %>
		<%= render :partial => 'pages/pageimage', :collection => @activity.book.pages, :locals => {:book => @activity.book} %>
	<% end %>
	
	<%= hidden_field :activity_type, :value => 'book' %>
	
	<%= submit_tag "Save Book", :class => "big-button blue" %>	
<% end %>

app/views/activities/_gameform.erb
<%= form_for @activity do |f| %>
	<% if @activity.errors.any? %>
		<div class="error-messages">
			<h2>Wait! There's a problem</h2>
			<ul>
				<% for message in @activity.errors.full_messsages do %>
					<li><%= message %></li>
				<% end %>
			</ul>	
		</div>
	<% end %>
	<p>
	<%= f.label 'Game Title' %>
	<%= f.text_field :title, :required => true %>
	</p>
	
	<%= fields_for 'activity[game_attributes]', @activity.game do |game_form| %>
		<p>
		<%= game_form.label 'Client ID (corresponds to game ID on iPad)' %>
		<%= game_form.text_field :client_id %>
		</p>	

	<% end %>
	
	<p>
	<%= f.label 'Publish to Toybox?' %>
	<%= f.radio_button :publish, '1' %>Yes <%= f.radio_button :publish, '0' %>No
	</p>
	
	<%= hidden_field :activity_type, :value => 'game' %>
	
	<%= submit_tag "Save Game", :class => "big-button blue" %>	
<% end %>

app/views/activities/editbook.erb
<h1>Edit Book</h1>

<%= render :partial => 'bookform', :locals => {:activity => @activity} %>

app/views/activities/editgame.erb
<h1>Edit Game</h1>

<%= render :partial => 'gameform', :locals => {:activity => @activity} %>

app/views/activities/editorder.erb
<h1>Reorder Toybox Activities</h1>
 
<ul>
<% @activities.each do |activity| %>
  <li>
    <%= activity.toybox_order %> <%= activity.title %> 
  </li>
<% end %>
</ul>

app/views/activities/index.erb
<% content_for :javascript do %>
	<%= javascript_tag do %>
		// Sorting the list

		$(document).ready(function(){
			$('#activity-list').sortable({
				axis: 'y',
				dropOnEmpty: false,
				handle: '.handle',
				cursor: 'crosshair',
				items: 'li',
				opacity: 0.4,
				scroll: true,
				update: function(){
					$.ajax({
						type: 'post',
						data: $('#activity-list').sortable('serialize'),
						dataType: 'script',
						complete: function(request){
						$('#activity-list').effect('highlight');
					},
					url: '/activities/sort'})
					}
				});
		});
	<% end %>
<% end %>

<h1>Toybox Activities</h1>

<div id='activity-list'>
	<ul>
	<% @activities.each do |activity| %>
	  <li id="activity_<%= activity.id %>">
	    <%= activity.title %> [<%= activity.id %>] - 
			<%= link_to 'Edit', edit_activity_path(activity) %> *** 
			<%= link_to 'Destroy', activity, :confirm => 'Are you sure?', :method => :delete %> **
			<span class="handle">[drag to reorder]</span>
	  </li>
	<% end %>
	</ul>
</div>

<%= link_to 'Create a new book', newactivity_path(:activity_type => "book") %> *** 
<%= link_to 'Create a new game', newactivity_path(:activity_type => "game") %> 

app/views/activities/newbook.erb
<h1>Create a New Book</h1>

<%= form_for @activity do |f| %>
	<% if @activity.errors.any? %>
		<div class="error-messages">
			<h2>Wait! There's a problem</h2>
			<ul>
				<% for message in @activity.errors.full_messsages do %>
					<li><%= message %></li>
				<% end %>
			</ul>	
		</div>
	<% end %>
	<p>
	<%= f.label 'Book Title' %>
	<%= f.text_field :title, :required => true %>
	</p>
	
	<%= fields_for 'activity[book_attributes]', @activity.book do |book_form| %>
		<p>
		<%= book_form.label 'Name of S3 image directory' %>
		<%= book_form.text_field :image_directory, :required => true %>
		</p>	
		<p>
		<%= book_form.label 'Number of Pages' %>
		<%= select_tag :num_pages, "<option>1</option><option>2</option><option>3</option><option>4</option><option>5</option><option>6</option><option>7</option><option>8</option><option>9</option><option>10</option><option>11</option><option>12</option><option>13</option><option>14</option><option>15</option><option>16</option><option>17</option><option>18</option><option>19</option><option>20</option>".html_safe, :include_blank => true, :required => true %>
		</p>
		<p>
		<%= book_form.check_box :image_only, {:checked => true, :required => true} %>
		<%= book_form.label 'Image-only? (i.e. text is baked into the images)' %>
		</p>

	<% end %>
	
	<%= submit_tag "Save Book", :class => "big-button blue" %>	
<% end %>

app/views/activities/newgame.erb
<h1>Create a New Game</h1>

<%= render :partial => 'gameform', :locals => {:activity => @activity} %>