config/routes.rb
Semiralabs::Application.routes.draw do 

  match 'playdate' => 'games#playdate'
  match 'update_playdate' => 'games#updatePlaydate'
  match 'feedbacks' => 'feedback#create'

  devise_for :users, :controllers => { :sessions => "sessions", :passwords => "passwords" }
  resources :users, :only => [:show] do
    collection do
      get 'search'
      get 'allofplaytellsusers'
    end
  end
  match 'remove_user' => 'users#remove'
  match 'remove_earlyuser' => 'users#remove_earlyuser'
  match 'users_email_list' => 'users#users_email_list'
  match 'earlyusers_email_list' => 'users#earlyusers_email_list'
  
  resources :friendships do
    collection do
      post 'add'
    end
  end
  match "remove_friendship" => 'friendships#remove'

  namespace :api do
    match 'token/update' => 'tokens#update'
    resources :tokens, :only => [:create, :destroy]

    match 'playdatephoto/all_photos' => 'playdatephotos#all_photos'
    resources :playdatephotos, :only => [:create]

    resources :postcards, :only => [:create]
    match 'postcard/all_photos' => 'postcards#all_photos'
    match 'postcard/num_new_photos' => 'postcards#num_new_photos'

    match 'update_settings' => 'settings#update'
    match 'settings/version_check' => 'settings#version_check'
    match 'twilio_incoming' => 'twilio#incoming'
    match 'twilio_token' => 'twilio#capability_token'
    match 'tokbox_tokens' => 'tokbox#tokbox_tokens'
    match 'playdate_players' => 'playdate#playdate_players'
    match 'playdate/redial' => 'playdate#redial'
    match 'playdate/turn_page' => 'playdate#turn_page'
    match 'playdate/change_book' => 'playdate#change_book'
    match 'playdate/close_book' => 'playdate#close_book'
    match 'playdate/finger_tap' => 'playdate#finger_tap'
    match 'playdate/finger_end' => 'playdate#finger_end'
    match 'playdate/create' => 'playdate#create'
    match 'playdate/details' => 'playdate#show'
    match 'playdate/disconnect' => 'playdate#disconnect'
    match 'playdate/join' => 'playdate#join'
    match 'playdate/check_for_playdate' => 'playdate#check_for_playdate'
    match 'playdate/channel_stats' => 'playdate#channel_stats'
    match 'playdate/generate_ot_session' => 'playdate#generate_ot_session'
    match 'activities/list' => 'activities#list'
    match 'books/list' => 'books#list'
    match 'books/get_nux_book' => 'books#get_nux_book'
    match 'users/all_friends' => 'users#all_friends'
    match 'users/get_status' => 'users#get_status'
    match 'users/create_friendship' => 'users#create_friendship'
    match 'users/create' => 'users#create'
    match 'users/update' => 'users#update'
    match 'users/show' => 'users#show'
    match 'users/change_password' => 'users#change_password'
    match 'users/email_check' => 'users#email_check'
    match 'users/reset_password' => 'users#reset_password'
    match 'users/sign_in' => 'users#sign_in'
    match 'pusher/hook' => 'pusher#hook'
    match 'contacts/create_list' => 'contacts#create_list'
    match 'contacts/show' => 'contacts#show'
    match 'contacts/show_related' => 'contacts#show_related'
    match 'contacts/notify' => 'contacts#notify'
    match 'friendship/create' => 'friendships#create'
    match 'friendship/accept' => 'friendships#accept'
    match 'friendship/decline' => 'friendships#decline'

    match 'games/tictactoe/new_game' => 'tictactoe#new_game'
    match 'games/tictactoe/place_piece' => 'tictactoe#place_piece'
    match 'games/tictactoe/spaces_to_json' => 'tictactoe#spaces_to_json'
    match 'games/tictactoe/indicators_to_json' => 'tictactoe#indicators_to_json'
    match 'games/tictactoe/board_to_json' => 'tictactoe#board_to_json'
    match 'games/tictactoe/end_game' => 'tictactoe#end_game'

    match 'games/memory/new_game' => 'memory#new_game'
    match 'games/memory/play_turn' => 'memory#play_turn'
    match 'games/memory/end_game' => 'memory#end_game'

    match 'games/matching/new_game' => 'matching#new_game'
    match 'games/matching/play_turn' => 'matching#play_turn'
    match 'games/matching/end_game' => 'matching#end_game'

    match 'games/hangman/new_game'  => 'hangman#new_game'
    match 'games/hangman/play_turn' => 'hangman#play_turn'
    match 'games/hangman/end_game'  => 'hangman#end_game'

    match 'contacts/show_related' => 'contacts#show_related'
    match 'contacts/notify' => 'contacts#notify'
    match 'contacts/search' => 'contacts#search'
    
  end
  
  match 'pusher/auth' => 'pusher#auth'
  match '/ipad' => 'ipad#index'
  match '/iPad' => 'ipad#index'
  match '/memory' => 'ipad#index'

  
  match 'early_access' => 'application#earlyAccess' 
  match 'timeline' => 'application#timeline'  
  
  authenticated do
    root :to => 'users#show'
  end 
  root :to => 'application#index'
  
  resources :books do
    resources :pages
  end
  
  resources :activities do
    post :sort, :on => :collection
  end
  match 'newactivity/:activity_type' => 'activities#newactivity', :as => 'newactivity'
    
  match 'update_page' => 'games#updatePage'
  match 'update_from_playdate' => 'games#updateFromPlaydate'
  match 'clear_playdate' => 'games#clearPlaydate'
  match 'disconnect_playdate' => 'games#disconnectPlaydate'
  match 'playdate_requested' => 'games#playdateRequested'
  match 'playdate_disconnected' => 'games#playdateDisconnected'
  
  match 'memory' => 'games#memory'
  match 'update_game' => 'games#updateGame'
  match 'update_game_from_session' => 'games#updateGameFromSession'
  match 'set_time' => 'games#setTime' #for youtube videos
  match 'check_time' => 'games#checkTime'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  respond_to :html, :xml, :tablet, :json 
  
  before_filter :prepare_for_tablet
  helper_method :resource, :resource_name, :devise_mapping, :tablet_device?
    
  before_filter :pusher, :only => [:turnPage]
  before_filter :initialize_mixpanel
  
  layout :specify_layout
  
  def index 
     @earlyUser = EarlyUser.new
  end
  
  def earlyAccess
    user2 = params[:user2]
    
    unless params[:early_user][:email].blank? 
      earlyUser = EarlyUser.find_or_create_by_email(params[:early_user])
      puts 'here1'
      if earlyUser.qualifies? and !user2[:email2].blank? 
        if user2[:email2] == params[:early_user][:email]
          render :json => {:message=>"error-email"}
          return
        else
          puts "here"
          user1 = User.find_or_create_by_email(:email => params[:early_user][:email], 
                               :password => "rg", 
                               :username => params[:early_user][:username],
                               :status => User::WAITING_FOR_UDID)
          user2 = User.find_or_create_by_email(:email => user2[:email2], 
                               :password => "rg", 
                               :username => user2[:username2], 
                               :status => User::WAITING_FOR_UDID)
          if user2.save and user1.save                 
            user1.friendships.create!(:friend_id => user2.id)
            UserMailer.betauser_welcome(user1).deliver
            UserMailer.betainvitee_welcome(user1, user2).deliver

            render :json => {:message=>"active_user"}
            return
          else
            render :json => {:message=>"error-email"}
            return
          end
        end
      else      
        if earlyUser.save
          UserMailer.earlyuser_welcome(earlyUser).deliver
          render :json => {:message=>"early_user"} 
          return
        else 
          render :json => {:message=>"error-fields"}
          return
        end
      end   
    end
    
    render :json => false
    
  end
  
  def timeline
  end
  
  def specify_layout
    if devise_controller?
      "devise"
    else
      "application"
    end
  end
    
private  

  def tablet_device?
    request.user_agent =~ /iPad/
  end
  
  def prepare_for_tablet
    #request.format = :tablet if tablet_device?
  end

  # for use with devise
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  
  def save_path_and_authenticate_user
    if current_user.blank?
      session[:user_return_to] = request.url
      authenticate_user!
    end
  end
  
  def after_sign_in_path_for(user)
    if !params[:device_token].blank?
      d = DeviceToken.find_or_create_by_user_id({ :user_id => user.id })
      if d.token != params[:device_token]
        d.token = params[:device_token] 
        d.save!
        Urbanairship.register_device(params[:device_token])
      end
    end
    
    if session[:user_return_to]
      sign_in_url = url_for(:action => 'new', :controller => '/sessions', :only_path => false, :protocol => 'http')     
      session[:user_return_to] if session[:user_return_to] != sign_in_url
    else
      user_path user.id
    end
  end
  
  # returns the playdate if there is a playdate request for the current user. should be used only when checking for a playdate request (not to get the current playdate session)
  def requesting_playdate
    @playdate ||= Playdate.findActivePlaydate(current_user) 
  end
  
  # returns the playdate currently in the session
  def current_playdate
    @playdate ||= Playdate.find(session[:playdate])
  end
  
  def pusher
    if !@pusher_key
      @pusher_key = Pusher.key
    end
  end
  
  # PLAYDATE SHARED METHODS
  
  # expected params: book_id, page_num
  # sends change_book pusher event
  def changeBook
    getBook(params[:book_id])
    if @book.blank? 
      return false;
    end
    @playdate.page_num = params[:page_num]
    @playdate.save
    Pusher[@playdate.pusher_channel_name].trigger('change_book', {
      :data => @book.to_json(:include => :pages),
      :book => @book.id,
      :player => current_user.id,
      :page => params[:page_num]
    })
  end
  
  # loads a book for a playdate.   
  def getBook(id)
    @book = Book.find(id)
    if @book.blank?
      return false
    end
    @playdate.book_id = id
    @playdate.save
  end
  
  # expected params: new_page_num
  # sends a pusher event to turn to new_page_num
  def turnPage
    @playdate.page_num = params[:new_page_num]
    @playdate.save
    Pusher[@playdate.pusher_channel_name].trigger('turn_page', {
      :player => current_user.id,
      :page => params[:new_page_num]
    })
  end
  
  # sends a pusher event to close book
  def closeBook
    Pusher[@playdate.pusher_channel_name].trigger('close_book', {
      :player => current_user.id,
      :book => params[:book_id],
    })
  end
  
  # sends a pusher event on playdate channel to end playdate
  def endPlaydate
    # Channel notification to players in this playdate
    Pusher[@playdate.pusher_channel_name].trigger('end_playdate', {:playdate => @playdate.id, :player => current_user.id})
    
    # Rendezvous notification to everyone else
    initiator = User.find(@playdate.player1_id)
    playmate = User.find(@playdate.player2_id)
    Pusher["presence-rendezvous-channel"].trigger('playdate_ended', {
      :playdateID           => @playdate.id,
      :pusherChannelName    => @playdate.pusher_channel_name,
      :initiatorID          => initiator.id,
      :initiator            => initiator.username,
      :playmateID           => playmate.id,
      :playmateName         => playmate.username,
      :tokboxSessionID      => @playdate.video_session_id,
      :tokboxInitiatorToken => @playdate.tokbox_initiator_token,
      :tokboxPlaymateToken  => @playdate.tokbox_playmate_token
    })
    
    # DB update
    @playdate.disconnect
  end

  private
  def initialize_mixpanel
    @mixpanel = Mixpanel::Tracker.new(ENV['MIXPANEL_KEY'], { :env => request.env })
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

#depricated
  def getPageImageFilePath(directory, pageNum) 
    if (pageNum.to_i > 0)
      "#{S3_BUCKET_NAME}/books/#{directory}/page#{pageNum}"
    elsif (pageNum.to_i == 0)
      "#{S3_BUCKET_NAME}/books/#{directory}/cover_front"
    end
  end

#depricated
  def getImageFilePath(name)
    "https://ragatzi.s3.amazonaws.com/" + name;
  end
  
  def fellowPlayers()
    return User.all
  end
end

app/views/application/_keepsakes.erb
<div class="keepsakes-container hidden">
	<div class="keepsakes-header">
		<div class="photo-metadata">
			<p class="date inline-block">March 5, 2011</p>
			<p class="separator inline-block">&#149;</p>
			<p class="age inline-block">Jenna is 8 years old</p>
		</div>
		<div class="title-bar">
			<div class="photo-count inline-block fl">
				<p class="photos-icon inline-block"></p>
				<p class="number-text inline-block">2</p>
				<p class="number-text of inline-block">OF</p>
				<p class="number-text inline-block">22</p>
			</div>
			<div class="inline-block title">You and Alana read Grandma and Me</div>
			<div class="close-link inline-block fr"></div>
		</div>
	</div>
	<div class="photo-viewer"></div>
</div>

app/views/application/_sign-up.erb
<div class="beta-sign-up">
	<div class="sign-up-badge inline-block">
		<%= image_tag "homepage/sign_up_badge.png", :alt => "Sign up for the PlayTell beta!" %>
	</div>
	<div id="sign-up-form" class="inline-block">
		<p class="invisible error-text error-text-signup">Please enter your name and a valid email address.</p>
		<input type="text" class="name" id="name" placeholder="name">
		<input type="email" class="email" id="email" placeholder="email">
		<div class="signup-button-container"><p class="inline"><a href="#" class="homepage-sprite early-access-submit"></a></p></div>
	</div>
	<div class="social-elements inline-block"></div>
</div>

app/views/application/_survey.erb
<div id="ext-sign-up-form">
<div id="step1" class="">
	<h3>Short Sign-Up Survey</h3>

	<p class="required">Required</p>
	<div class="chunk" id="owns_iPad">
		<p class="error-text error-text-required hidden">Please answer the question below.</p>
		
		<p class="question">Do you own an iPad?</p> 
		<div><input type="radio" name="owns_iPad" value="1" class="answer"><p class="answer-text">Yes</p></div>
		<div><input type="radio" name="owns_iPad" value="0" class="answer"><p class="answer-text">No</p></div>
	</div>
	
	<p class="required">Required</p>
	<div class="chunk" id="has_kids">
		<p class="error-text error-text-required hidden">Please answer the question below.</p>
			
		<p class="question">Which of the following describes you?</p>
		<div>
		<input type="radio" name="has_kids" value="1" class="answer">
		<p class="answer-text">I have children younger than 8 years old</p>
		</div>
		<div>
		<input type="radio" name="has_kids" value="2" class="answer">
		<p class="answer-text">I video chat with children that are younger than 8 years old</p>
		</div>
		<div>
		<input type="radio" name="has_kids" value="0" class="answer">
		<p class="answer-text">None of the above</p>
		</div>
	</div>
	
	<div class="bottom-button"><p><a href="#" id="beta-form-next" class="homepage-sprite"></a></p></div>
</div>

<div id="step2" class="hidden">
	<h3>Sign-Up Your Family</h3>
	
	<p class="required">Required</p>
	<div class="chunk" id="sign-up-family">
		<p class="error-text error-text-required hidden">You must invite at least one family member to play with.</p>
		<p class="error-text error-text-valid hidden">Please enter your name and a valid email address.</p>
		
		<p class="question">Who would you like to read with on PlayTell?</p> 
		<input type="text" class="answer name" id="username2" placeholder="name or nickname">
		<input type="email" class="answer email" id="email2" placeholder="email">
	</div>
	
	<div class="chunk hidden" id="sign-up-family-optional">
		<p class="question">Any other family you would like to invite?</p>
		<input type="text" class="answer name" id="username2" placeholder="name or nickname">
		<input type="email" class="answer email" id="email2" placeholder="email">
	</div>
	
	<div class="bottom-button bottom-button-first"><p><a class="homepage-sprite close cancel"></a></p></div>
	<div class="bottom-button"><p><a class="homepage-sprite" id="beta-form-submit"></a></p></div>
	
</div>

<div id="step3" class="hidden">
	<h3>Thank You</h3>
	
	<%= image_tag "homepage/balloon.png", :class=>"fr" %>
	<div class="thanks fr">
		<p class="top-thanks top-thanks-full hidden">You and your family members will receive an email with a link to download the PlayTell app.</p>
		<p class="top-thanks top-thanks-individual hidden">You're on the list! We'll be in touch soon.</p>
		<p class="bottom-thanks">Thanks for signing up to PlayTell!</p>
	</div>
	<br>

	<div class="bottom-button"><p><a class="homepage-sprite close"></a></p></div>
	
</div>
	
<div id="loader" class="hidden loading"></div>

app/views/application/_survey_old.erb
<div id="ext-sign-up-form">
	<div class="errors-container">
		<div class="error error-ext-survey-fields">Please answer all questions</div> 
		<div class="error error-ext-survey-email"> Please enter a unique, valid email</div>
	</div>
	<h3>SIGN UP</h3>
	<hr />
	<div class="chunk">
		<%= image_tag 'error_arrow_right.png', :class=>"errow errow-ext-survey "%>
		<p class="question" id="owns_iPad">Do you own an iPad?</p> 
	</div><br />
	<input type="radio" name="owns_iPad" value="1" class="answer"><p class="answer-text">Yes</p><br />
	<input type="radio" name="owns_iPad" value="0" class="answer"><p class="answer-text">No</p>
	<br />
	
	<div class="chunk">
		<%= image_tag 'error_arrow_right.png', :class=>"errow errow-ext-survey "%>
		<p class="question">Which of the following describes you?</p>
	</div></br>
	<input type="radio" name="has_kids" value="1" class="answer">
		<p class="answer-text">I have children younger than 8 years old</p>
	<br />
	<input type="radio" name="has_kids" value="2" class="answer">
		<p class="answer-text">I video chat with children that are younger than 8 years old</p>
	<br />
	<input type="radio" name="has_kids" value="0" class="answer">
		<p class="answer-text">None of the above</p>
	<br />
	<div class="chunk">
		<%= image_tag 'error_arrow_right.png', :class=>"errow errow-ext-survey "%>
		<p class="question">Who would you like to invite to play with on PlayTell?</p> 
	</div><br />
		<input type="text" class="answer name" id="username2" placeholder="name or nickname">
	<br />
		<input type="email" class="answer email" id="email2" placeholder="email">
	<br />

	<p><button class="blue big-button" id="alpha-form-submit">Send</button></p>
</div>
<div id="thank-you-early" class="hidden">
	<%= image_tag "thanks-balloon.png"%>
	<h3>Thanks! You're on the list.</h3>
	<p>We'll be in touch soon.</p> 
</div>	
<div id="thank-you-active" class="hidden">
	<%= image_tag "thanks-balloon.png"%>
	<h3>You're in!</h3>
	<p>Further instructions are on their way to your email inbox. Get ready to play!</p> 
</div>	
<div id="loader" class="hidden loading"></div>

app/views/application/_values.erb
<div class="hidden" id="values">
	<p id="pusher-key"><%= @pusher_key if @pusher_key %></p>
	<p id="pusher-channel-name"><%= @playdate.pusher_channel_name if @playdate && @playdate.pusher_channel_name %></p>
	<p id="current-user"><%= current_user.id if current_user %></p>
</div>

app/views/application/earlyAccess.js.erb
hide('loader');
hide('new_early_user');
//hide('access-lightbox-text');
$('#thank-you').fadeIn("fast");

app/views/application/index.erb
<% content_for :head do %>	

<script type="text/javascript">

	//size the splash image to the window height
$(document).ready(function() {
	$('img#ribbons').load(function() {
			
		var h, winW, imgPos;
		
		if (screen.width < 767) {
			w = $(document).width() * 1.8;
			h = $(document).height() * .9;
			
			$('#block-splash').css({'min-height' : h});
			$('#block-splash img').css({'min-height' : h});
			$('#block-splash img').css({'min-width' : w});
			winW = screen.width;
		}
		else if ($(document).width() > 767) {
			h = $(document).height();
			$('#block-splash').css({'min-height' : h});
			$('#block-splash img').css({'min-height' : h});
			winW = $(document).width();
		}
		
		var imgW = $('img#ribbons').width();
		if (screen.width < 767) {
			imgPos = (winW - imgW) / 3.25;
		} else {
			imgPos = (winW - imgW);			
		}
	
		$('#block-splash img').offset( { top: 0, left: imgPos } );
		show('ribbons');
		show('slide_1');
		$('#bottom-row').removeClass("invisible");
		
		setTimeout(function() {
			show('slide_2');
			$('#slide_1').hide("slide", { direction: "left" }, 'slow');
			}, 4000);
		setTimeout(function() {
			show('slide_3');
			$('#slide_2').hide("slide", { direction: "left" }, 'slow');
			}, 8000);
			
	});
});

</script>

<% end %>	
	<div class="splash-container">
		<div id="block-splash" class="center">
			<%= image_tag "http://playtell.s3.amazonaws.com/HomePage/book.png", :class => "center hidden", :id => "slide_3" %>
			<%= image_tag "http://playtell.s3.amazonaws.com/HomePage/game.png", :class => "center hidden", :id => "slide_2" %>
			<%= image_tag "http://playtell.s3.amazonaws.com/HomePage/dialpad.png", :class => "center hidden", :id => "slide_1" %>
			<%= link_to image_tag("http://playtell.s3.amazonaws.com/HomePage/iPad-Ribbons.png", :class => "center hidden", :id => "ribbons"), 'http://itunes.apple.com/us/app/id570304295', :target => "_blank" %>
		</div>
	</div>

<footer class="invisible" id="bottom-row">
	<ul class="nav-list">
		<li><%= link_to image_tag("http://playtell.s3.amazonaws.com/HomePage/facebook.png", :class => "center"), 'http://www.facebook.com/playtell', :target => "_blank" %></li>
		<li><%= link_to image_tag("http://playtell.s3.amazonaws.com/HomePage/twitter.png", :class => "center"), 'https://twitter.com/#!/GoPlayTell', :target => "_blank" %></li>
		<li><%= link_to image_tag("http://playtell.s3.amazonaws.com/HomePage/pinterest.png", :class => "center"), 'http://pinterest.com/playtell/', :target => "_blank" %></li>
		<li><%= link_to image_tag("http://playtell.s3.amazonaws.com/HomePage/angellist.png", :class => "center"), 'http://angel.co/playtell', :target => "_blank" %></li>
	</ul>
	<div class="hidden">
		<li><a href="mailto:info@playtell.com">Contact Us</a></li>
		<li><a href="#">Terms of Service</a></li>
		<li><a href="#">Privacy Policy</a></li>
	</div>
</footer>

app/views/application/index.html.erb
<% content_for :head do %>
	<link href='http://fonts.googleapis.com/css?family=Lato:100,400|Quicksand:300,400' rel='stylesheet' type='text/css'>	

	<script type="text/javascript">
	  $(document).ready(function() {

	    //Default
	    $("#jump").click(function (event) {	
			$(".mainContainer").animate(
				{ scrollTop: 100 }, "slow", "easeOutBack" );
			event.preventDefault();
			return false;
		});
	  });
	
	$(function () {
	  var h = $(window).height();
	  $('#block-splash').height(h);
	
	  var img = new Image();
	  $(img)
	    .load(function () {
	      $(this).hide();
		  $(this).appendTo('#block-splash');
	      $(this).show();
	    })

	    .error(function () {
	      // notify the user that the image could not be loaded
	    })

	    .attr('src', '/images/splash_ipad.png')
	    .attr('style', 'height: ' + h + 'px');
	});	
	
	 </script>
	
<% end %>

<div class="nav">
	<a href="#"><%= image_tag 'logo.png' %></a>
	<ul>
		<!--<li><a href="#">Home</a></li>
		<li><a href="#">Product</a></li>
		<li><a href="#">Team</a></li>
		<li><a href="#">Contact</a></li>
		<li><a href="#"><button>Request Invitation</button></a></li>-->
	</ul>
</div>
<div class="landing-page" id="landingpage">
	<div id="block-splash">
	</div>
	<div id="block-product">
	</div>
	<div id="block-team">
	</div>
	<div id="block-sign-up">
		<div class="alpha-sign-up" id="sign-up">
			<%= form_for @earlyUser, :url => early_access_path, :remote => true do |f| %>
			<h3>Request an Invitation</h3>	
				<%= f.email_field :email %><br />
				<%= submit_tag "Sign me up!", :class => "blue big-button", :id => "early-access-submit" %>
				<div id="loader" class="hidden loading"></div>
			<% end %>
			<div id="thank-you" class="hidden">
				<p>Thanks! You're on the list.</p>
				<p>We'll be in touch soon.</p> 
			</div>
		</div>
	</div>
</div>

app/views/application/timeline.erb
<% content_for :head do %>

	<script src="http://js.pusher.com/1.11/pusher.min.js"></script>
	<%= javascript_include_tag 'pusher', 'playdate' %>

	<script type="text/javascript">
		var tablet = false;
		var pusher;
		var playdateChannel;
		
		$(document).ready(function() {
			<% if tablet_device? %>
				tablet = true;
			<% end %>
			pusher = new Pusher($('#pusher-key').html()); 			
			checkForPlaydateRequest(); 
			enableButtons();
			
			$('.photos-container').on(tablet ? 'touchstart' : 'click', function() {
				$('.overlay').show();
				$('.keepsakes-container').fadeIn();
			});
		});

	</script>
<% end %>

<div class="timeline-container">
	<div class="timeline-bar">
	</div>
	<div class="timeline-selector">
	</div>
	<div class="photos-container">
	</div>
	<%= render :partial => "games/toybox" %>
	<div class="overlay hidden"></div>
	<%= render :partial => "keepsakes" %>
</div>


<div class="lightbox hidden" id="join-lightbox">
	<h1 id="player-name"></h1>
	<h2>wants to play!</h2>
	<a href="#" id="playdate-target">
		<button class="blue big-button">Join Playdate</button>
	</a>
</div>