config/routes.rb
Semiralabs::Application.routes.draw do 

  match 'playdate' => 'games#playdate'
  match 'update_playdate' => 'games#updatePlaydate'
  match 'feedbacks' => 'feedback#create'

  devise_for :users, :controllers => { :sessions => "sessions", :passwords => "passwords" }
  resources :users, :only => [:show] do
    collection do
      get 'search'
      get 'allofplaytellsusers'
    end
  end
  match 'remove_user' => 'users#remove'
  match 'remove_earlyuser' => 'users#remove_earlyuser'
  match 'users_email_list' => 'users#users_email_list'
  match 'earlyusers_email_list' => 'users#earlyusers_email_list'
  
  resources :friendships do
    collection do
      post 'add'
    end
  end
  match "remove_friendship" => 'friendships#remove'

  namespace :api do
    match 'token/update' => 'tokens#update'
    resources :tokens, :only => [:create, :destroy]

    match 'playdatephoto/all_photos' => 'playdatephotos#all_photos'
    resources :playdatephotos, :only => [:create]

    resources :postcards, :only => [:create]
    match 'postcard/all_photos' => 'postcards#all_photos'
    match 'postcard/num_new_photos' => 'postcards#num_new_photos'

    match 'update_settings' => 'settings#update'
    match 'settings/version_check' => 'settings#version_check'
    match 'twilio_incoming' => 'twilio#incoming'
    match 'twilio_token' => 'twilio#capability_token'
    match 'tokbox_tokens' => 'tokbox#tokbox_tokens'
    match 'playdate_players' => 'playdate#playdate_players'
    match 'playdate/redial' => 'playdate#redial'
    match 'playdate/turn_page' => 'playdate#turn_page'
    match 'playdate/change_book' => 'playdate#change_book'
    match 'playdate/close_book' => 'playdate#close_book'
    match 'playdate/finger_tap' => 'playdate#finger_tap'
    match 'playdate/finger_end' => 'playdate#finger_end'
    match 'playdate/create' => 'playdate#create'
    match 'playdate/details' => 'playdate#show'
    match 'playdate/disconnect' => 'playdate#disconnect'
    match 'playdate/join' => 'playdate#join'
    match 'playdate/check_for_playdate' => 'playdate#check_for_playdate'
    match 'playdate/channel_stats' => 'playdate#channel_stats'
    match 'playdate/generate_ot_session' => 'playdate#generate_ot_session'
    match 'activities/list' => 'activities#list'
    match 'books/list' => 'books#list'
    match 'books/get_nux_book' => 'books#get_nux_book'
    match 'users/all_friends' => 'users#all_friends'
    match 'users/get_status' => 'users#get_status'
    match 'users/create_friendship' => 'users#create_friendship'
    match 'users/create' => 'users#create'
    match 'users/update' => 'users#update'
    match 'users/show' => 'users#show'
    match 'users/change_password' => 'users#change_password'
    match 'users/email_check' => 'users#email_check'
    match 'users/reset_password' => 'users#reset_password'
    match 'users/sign_in' => 'users#sign_in'
    match 'pusher/hook' => 'pusher#hook'
    match 'contacts/create_list' => 'contacts#create_list'
    match 'contacts/show' => 'contacts#show'
    match 'contacts/show_related' => 'contacts#show_related'
    match 'contacts/notify' => 'contacts#notify'
    match 'friendship/create' => 'friendships#create'
    match 'friendship/accept' => 'friendships#accept'
    match 'friendship/decline' => 'friendships#decline'

    match 'games/tictactoe/new_game' => 'tictactoe#new_game'
    match 'games/tictactoe/place_piece' => 'tictactoe#place_piece'
    match 'games/tictactoe/spaces_to_json' => 'tictactoe#spaces_to_json'
    match 'games/tictactoe/indicators_to_json' => 'tictactoe#indicators_to_json'
    match 'games/tictactoe/board_to_json' => 'tictactoe#board_to_json'
    match 'games/tictactoe/end_game' => 'tictactoe#end_game'

    match 'games/memory/new_game' => 'memory#new_game'
    match 'games/memory/play_turn' => 'memory#play_turn'
    match 'games/memory/end_game' => 'memory#end_game'

    match 'games/matching/new_game' => 'matching#new_game'
    match 'games/matching/play_turn' => 'matching#play_turn'
    match 'games/matching/end_game' => 'matching#end_game'

    match 'games/hangman/new_game'  => 'hangman#new_game'
    match 'games/hangman/play_turn' => 'hangman#play_turn'
    match 'games/hangman/end_game'  => 'hangman#end_game'

    match 'contacts/show_related' => 'contacts#show_related'
    match 'contacts/notify' => 'contacts#notify'
    match 'contacts/search' => 'contacts#search'
    
  end
  
  match 'pusher/auth' => 'pusher#auth'
  match '/ipad' => 'ipad#index'
  match '/iPad' => 'ipad#index'
  match '/memory' => 'ipad#index'

  
  match 'early_access' => 'application#earlyAccess' 
  match 'timeline' => 'application#timeline'  
  
  authenticated do
    root :to => 'users#show'
  end 
  root :to => 'application#index'
  
  resources :books do
    resources :pages
  end
  
  resources :activities do
    post :sort, :on => :collection
  end
  match 'newactivity/:activity_type' => 'activities#newactivity', :as => 'newactivity'
    
  match 'update_page' => 'games#updatePage'
  match 'update_from_playdate' => 'games#updateFromPlaydate'
  match 'clear_playdate' => 'games#clearPlaydate'
  match 'disconnect_playdate' => 'games#disconnectPlaydate'
  match 'playdate_requested' => 'games#playdateRequested'
  match 'playdate_disconnected' => 'games#playdateDisconnected'
  
  match 'memory' => 'games#memory'
  match 'update_game' => 'games#updateGame'
  match 'update_game_from_session' => 'games#updateGameFromSession'
  match 'set_time' => 'games#setTime' #for youtube videos
  match 'check_time' => 'games#checkTime'
  

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  NO=1
  SORTA=2
  YES=3  
end

app/controllers/feedback_controller.rb
class FeedbackController < ApplicationController
  def new
    @feedback = Feedback.new
  end

  def create
    unless params[:feedback][:rating].blank? and params[:feedback][:comment].blank?
      @feedback = Feedback.new(params[:feedback])
      @feedback.save
    end
    respond_to do |format|
      format.js 
    end
  end

end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/views/feedback/_form.erb
<%= form_for @feedback, :remote => true do |f| %>
	<% if @feedback.errors.any? %>
		<div class="error-messages">
			<h2>Oops! There's a problem</h2>
			<ul>
				<% for message in @feedback.errors.full_messsages do %>
					<li><%= message %></li>
				<% end %>
			</ul>	
		</div>
	<% end %>
	
	<%= f.hidden_field :user_id, :value => @current_user.id %>
	<%# <%= f.hidden_field :playdate_id, :value => @playdate.id %>
	
	<p class="radio-label">
	<%= f.radio_button :rating, Feedback::YES %><%= f.label :yes, "Yep!" %>
	
	<%= f.radio_button :rating, Feedback::SORTA %><%= f.label :sorta, "Sorta" %>
	
	<%= f.radio_button :rating, Feedback::NO %><%= f.label :no, "Not really" %>
	</p>
	<p> <%= f.label :comment, "What can we do to make your playdates even better?" %></p>
	<p><%= f.text_area :comment, :size => "40x4" %></p>	
	
	<%= submit_tag "Send to PlayTell", :class => "blue button-bottom" %>
	
<% end %>	



<% if false%>
	
<%= form_for @playdatePhoto, :url => api_playdatephotos_path, :html => {:multipart => true} do |f| %>
	<p><%= f.file_field :photo %></p>
	<%= f.hidden_field :user_id, :value => @current_user.id %>
	<%= f.hidden_field :playdate_id, :value => @playdate.id %>
	
	
<% end %>
<% end %>

app/views/feedback/_form.html.erb
<%= form_for @feedback, :remote => true do |f| %>
	<% if @feedback.errors.any? %>
		<div class="error-messages">
			<h2>Oops! There's a problem</h2>
			<ul>
				<% for message in @feedback.errors.full_messsages do %>
					<li><%= message %></li>
				<% end %>
			</ul>	
		</div>
	<% end %>
	
	<%= f.hidden_field :user_id, :value => @current_user.id %>
	<%= f.hidden_field :playdate_id, :value => @playdate.id %>
	
	<p class="radio-label">
	<%= f.radio_button :rating, Feedback::YES %><%= f.label :yes, "Yep!" %>
	
	<%= f.radio_button :rating, Feedback::SORTA %><%= f.label :sorta, "Sorta" %>
	
	<%= f.radio_button :rating, Feedback::NO %><%= f.label :no, "Not really" %>
	</p>
	<p> <%= f.label :comment, "What can we do to make your playdates even better?" %></p>
	<p><%= f.text_area :comment, :size => "40x4" %></p>	
	<%= submit_tag "Send to Ragatzi", :class => "blue button-bottom" %>
	
<% end %>

app/views/feedback/create.erb
<h1>Feedback#create</h1>
<p>Find me in app/views/feedback/create.html.erb</p>

app/views/feedback/create.html.erb
<h1>Feedback#create</h1>
<p>Find me in app/views/feedback/create.html.erb</p>

app/views/feedback/new.erb
<h1>Feedback#new</h1>
<p>Find me in app/views/feedback/new.html.erb</p>

app/views/feedback/new.html.erb
<h1>Feedback#new</h1>
<p>Find me in app/views/feedback/new.html.erb</p>